[package]
name = "gojo"
version = "0.1.0"
license = "MIT"
keywords = ["starknet", "defi", "syntethics"]

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.0.2"

[tool.snforge]
exit_first = false
