[package]
name = "gojo"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = "2.0.1"
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[tool.snforge]
exit_first = true
